### ISSUE TITLE
How to view files in albula remotely

### ISSUE THREAD

**Issue by rheadric** [yugangzhang/CHX_Pipelines#18]
It should be possible to view raw data from the Eiger detector remotely (i.e. frommy laptop computer).  I was able to log in to box64-1-nsls2.bnl.gov with ssh -X and run albula.  But I don't know where to find the data from there.

**Comment by yugangzhang** [comment]
After ssh -X into box64-1, you should ssh into xf11id-srv1. After that, you can run albula and the data filename can be found in one pipeline by giving uid.

**Comment by rheadric** [comment]
That doesn't work for me.  I can login to xf11id-srv1 but when I run albula the display never opens.

My assumption is that port forwarding is needed.  I tried

     ssh -L 7777:xf11id-srv1:22 rheadric@box64-1.nsls2.bnl.gov cat -
followed by

    ssh -Xy -p 7777 rheadrick@localhost

The first step seems to work, but the second step fails to connect, so I can't go any further.

**Comment by rheadric** [comment]
We found a solution -- using x2go with the following parameters:

host: xf11id-srv1

check the box "use Proxy server for SSH connection"
 host:  ssh.nsls2.bnl.gov
 check the boxes: "Same login as on X2Go Server" and "Same Password as on X2Go Server"

Session type:  use the custom desktop MATE
